coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 10%
    patch: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: true
  require_head: true
  hide_project_coverage: false
  after_n_builds: 1
