coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 10%
    patch:
      default:
        target: 0%
        threshold: 0%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: true
  require_head: true
  hide_project_coverage: false
  show_critical_files: true
  after_n_builds: 1

comment_management:
  delete_old: true
  maintain_last: true
  delay_before_delete: 60
