export const STORAGE_PREFIX = "WITHIY_";

export const ACCESS_TOKEN_KEY = `${STORAGE_PREFIX}ACCESS_TOKEN`;
export const REFRESH_TOKEN_KEY = `${STORAGE_PREFIX}REFRESH_TOKEN`;

export const RECENT_LOGINED_SOCIAL_TYPE_KEY = `${STORAGE_PREFIX}RECENT_LOGINED_SOCIAL_TYPE`;

export const AGREE_TERMS_KEY = `${STORAGE_PREFIX}AGREE_TERMS`;

export const AUTH_CALLBACK_URL_KEY = `${STORAGE_PREFIX}AUTH_CALLBACK_URL`;
