import type { Metadata } from "next";

import MSWProvider from "@/app/providers/MSWProvider";
import { PretendardJP } from "@/app/ui/fontFace";

import "@/app/ui/styles/global.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={PretendardJP.variable}>
        <MSWProvider>{children}</MSWProvider>
      </body>
    </html>
  );
}
