name: "CI/CD"

on:
  push:
    branches:
      - develop

jobs:
  ci:
    name: Docker Build
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Export secrets to env/.env.development file
        uses: 0ndt/envfile@v2
        with:
          secrets: ${{ toJSON(secrets) }}
          file: env/.env.development

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            STAGE=dev
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ secrets.GHCR_USER }}/withiy-web:latest
            ghcr.io/${{ secrets.GHCR_USER }}/withiy-web:${{ github.sha }}

  cd:
    name: Argo CD
    needs: ci
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout withiy-infra repository
        uses: actions/checkout@v4
        with:
          repository: team-withiy/withiy-infra
          path: withiy-infra
          token: ${{ secrets.GHCR_TOKEN }}

      - name: commit & push
        run: |
          cd withiy-infra
          git config user.name "rldnd"
          git config user.email "gi981226@gmail.com"
          git config credential.helper store
          sed -i 's|ghcr.io/team-withiy/withiy-web:[^ ]*|ghcr.io/team-withiy/withiy-web:${{ github.sha }}|' web-prod.yaml
          git add web-prod.yaml
          git commit -m ":tada: deploy: withiy-web [${{ github.sha }}]"
          git push origin main
