name: Playwright Tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: e2e

    steps:
      - uses: actions/checkout@v4

      - name: Export secrets to env/.env.e2e file
        uses: 0ndt/envfile@v2
        with:
          secrets: ${{ toJSON(secrets) }}
          file: env/.env.e2e

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
