name: Storybook Tests
on: deployment_status
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v4

      - name: Export secrets to env/.env.test file
        uses: 0ndt/envfile@v2
        with:
          secrets: ${{ toJSON(secrets) }}
          file: env/.env.test

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run Storybook tests
        run: pnpm test:storybook
        env:
          SB_URL: "${{ github.event.deployment_status.target_url }}"
